import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to anon,authenticated,service_role;`);
const migration=await fs.readFile(new URL('../migrations/202609070001_world_classics_reader.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);console.log('PASS migration applies twice');
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}'),('${b}');`);
async function role(name,id=''){await db.exec(`reset role; set role ${name}; select set_config('request.jwt.claim.sub','${id}',false);`);}
async function denied(sql){await assert.rejects(db.exec(sql));}
await role('anon');for(const table of ['world_classics_cache','world_classics_translations','world_classics_bookmarks','world_classics_history','world_classics_limits','world_classics_translation_jobs'])await denied(`select * from public.${table}`);
await denied("insert into public.world_classics_cache(source,page_title,content,content_type,expires_at) values('japan','Test','{}','page',now())");
await denied("select public.wc_take_quota('x','x',60,1,2)");console.log('PASS anonymous cannot read user data or write global caches or call limiter');
await role('authenticated',a);
await db.exec(`insert into public.world_classics_bookmarks(user_id,source,work_title,page_title,chapter_title) values('${a}','japan','Work','Work/1','1');`);
await denied(`insert into public.world_classics_bookmarks(user_id,source,work_title,page_title,chapter_title) values('${b}','japan','Work','Work/2','2');`);
await denied(`update public.world_classics_bookmarks set user_id='${b}'`);
await denied("insert into public.world_classics_translations(source,page_title,original_hash,translation_mode,translated_content,model) values('japan','Work','"+'a'.repeat(64)+"','Natural','{}','test')");
await role('authenticated',b);
assert.equal((await db.query('select * from public.world_classics_bookmarks')).rows.length,0);
assert.equal((await db.query("update public.world_classics_bookmarks set chapter_title='evil' returning *")).rows.length,0);
assert.equal((await db.query('delete from public.world_classics_bookmarks returning *')).rows.length,0);
await role('authenticated',a);assert.equal((await db.query('select * from public.world_classics_bookmarks')).rows[0].chapter_title,'1');
console.log('PASS user A/B select, insert, update, delete RLS isolation');
for(let i=0;i<105;i++)await db.exec(`insert into public.world_classics_history(user_id,source,work_title,page_title,chapter_title) values('${a}','japan','Work','Work/${i}','${i}');`);
assert.equal((await db.query('select count(*)::int as n from public.world_classics_history')).rows[0].n,100);
await role('authenticated',b);assert.equal((await db.query('select * from public.world_classics_history')).rows.length,0);
await denied(`insert into public.world_classics_history(user_id,source,work_title,page_title,chapter_title) values('${a}','japan','Work','Work/evil','evil')`);
console.log('PASS history capped at 100; history RLS');
await role('service_role');
for(const expected of [true,true,false])assert.equal((await db.query("select public.wc_take_quota('translate','test',60,1,2) as ok")).rows[0].ok,expected);
await db.exec("update public.world_classics_limits set window_start=window_start-interval '2 minute',expires_at=now()-interval '1 minute'");
assert.equal((await db.query("select public.wc_take_quota('translate','test',60,1,2) as ok")).rows[0].ok,true);
assert.equal((await db.query(`select public.wc_claim_translation('job','${a}') as ok`)).rows[0].ok,true);
assert.notEqual((await db.query(`select public.wc_claim_translation('job','${b}') as ok`)).rows[0].ok,true);
await db.exec("update public.world_classics_translation_jobs set expires_at=now()-interval '1 second'");
assert.equal((await db.query(`select public.wc_claim_translation('job','${b}') as ok`)).rows[0].ok,true);
console.log('PASS durable quota, window expiry and translation lease');
await db.exec("insert into public.world_classics_cache(source,page_title,content,content_type,expires_at) values('japan','Work','{}','page',now())");
await denied("insert into public.world_classics_cache(source,page_title,content,content_type,expires_at) values('japan','Work','{}','page',now())");
for(const mode of ['Natural','Literal'])await db.exec(`insert into public.world_classics_translations(source,page_title,original_hash,translation_mode,translated_content,model) values('japan','Work','${'a'.repeat(64)}','${mode}','{}','test')`);
await db.exec(`insert into public.world_classics_translations(source,page_title,original_hash,translation_mode,translated_content,model) values('japan','Work','${'b'.repeat(64)}','Natural','{}','test')`);
console.log('PASS cache uniqueness, translation mode/hash independence');
await db.close();
