"use strict";const {CoverError,providerError}=require("./errors"),{normalizeResult}=require("./normalizer"),{createRegistry}=require("./registry");const health=new Map(),ORDER=["recraft","fal","openai","ideogram","stability","runware","huggingface"];
function needs(i){const n=["textToImage"];if(i.referenceImage)n.push("referenceImage");if(i.styleReference)n.push("styleReference");if(i.useNexoraStyle)n.push(i.nexoraStyleType==="recraft"?"customStyle":"lora");if(i.typographyMode==="ai")n.push("textRendering");return n}
function order(i){if(i.useNexoraStyle)return["fal","recraft","runware","huggingface","openai","ideogram","stability"];if(i.referenceImage||i.styleReference)return["openai","fal","recraft","runware","huggingface"];if(i.typographyMode==="ai")return["ideogram","openai","recraft","fal"];return ORDER}
function candidates(i,r=createRegistry(),provider){return(provider&&provider!=="auto"?[provider]:order(i)).map(id=>r.get(id)).filter(p=>p?.enabled&&needs(i).every(k=>p.capabilities[k])&&(!health.get(p.id)?.cooldownUntil||health.get(p.id).cooldownUntil<=Date.now()))}
async function runProvider(p,i,c={}){try{const r=normalizeResult(p.id,p.model,await p.generate(i,{...c,apiKey:p.apiKey}));health.set(p.id,{status:"healthy",cooldownUntil:0});return r}catch(e){const x=providerError(p.id,e),ms=x.code==="COVER_RATE_LIMITED"?60000:x.retryable?30000:0;health.set(p.id,{status:"degraded",code:x.code,cooldownUntil:Date.now()+ms});throw x}}
async function generateAuto(i,o={}){const r=o.registry||createRegistry(),ps=candidates(i,r);if(!ps.length)throw new CoverError("Tidak ada provider aktif yang mendukung konfigurasi ini.","COVER_NO_PROVIDER",503);const attempts=[];let last;for(const p of ps.slice(0,Math.min(3,o.maxAttempts||3))){try{return{result:await runProvider(p,i,o.context),attempts:[...attempts,p.id]}}catch(e){last=e;attempts.push(p.id);if(!e.retryable)break}}last.attempts=attempts;throw last}
async function generateManual(i,id,o={}){const p=candidates(i,o.registry||createRegistry(),id)[0];if(!p)throw new CoverError("Provider tidak aktif atau capability tidak cocok.","COVER_PROVIDER_DISABLED",400);return runProvider(p,i,o.context)}
async function generateComparison(i,ids,o={}){ids=[...new Set(ids)].slice(0,4);if(ids.length<2)throw new CoverError("Pilih minimal 2 provider.","COVER_COMPARE_SELECTION",400);const rows=await Promise.all(ids.map(async id=>{try{return{provider:id,ok:true,result:await generateManual({...i,variations:1},id,o)}}catch(e){return{provider:id,ok:false,error:{code:e.code,message:e.message}}}}));if(!rows.some(x=>x.ok))throw new CoverError("Semua provider perbandingan gagal.","COVER_COMPARE_FAILED",502);return rows}
const healthSnapshot=r=>[...r.values()].map(p=>({id:p.id,enabled:p.enabled,...(health.get(p.id)||{status:p.enabled?"ready":"disabled"})}));module.exports={candidates,generateAuto,generateManual,generateComparison,healthSnapshot,runProvider,_health:health};
