-- Nexora v5.1 — Analytics, feedback management, dan audit log
-- Jalankan setelah migration 003_admin_dashboard.sql. Aman dijalankan ulang.

alter table public.feedback
  add column if not exists internal_note text,
  add column if not exists admin_updated_by uuid references auth.users(id) on delete set null,
  add column if not exists replied_at timestamptz,
  add column if not exists resolved_at timestamptz;

create index if not exists feedback_updated_at_idx
  on public.feedback (updated_at desc);
create index if not exists feedback_category_status_idx
  on public.feedback (category, status, created_at desc);

create table if not exists public.tool_usage_events (
  id bigint generated by default as identity primary key,
  tool_id text,
  event_type text not null check (event_type in ('page_view', 'tool_open', 'external_open', 'tool_error')),
  visitor_hash text not null,
  session_hash text,
  path text not null default '/',
  referrer_host text,
  country_code text,
  device_type text,
  browser text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

alter table public.tool_usage_events enable row level security;

create index if not exists tool_usage_events_time_idx
  on public.tool_usage_events (occurred_at desc);
create index if not exists tool_usage_events_tool_time_idx
  on public.tool_usage_events (tool_id, occurred_at desc);
create index if not exists tool_usage_events_visitor_time_idx
  on public.tool_usage_events (visitor_hash, occurred_at desc);
create index if not exists tool_usage_events_type_time_idx
  on public.tool_usage_events (event_type, occurred_at desc);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  admin_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  before_data jsonb,
  after_data jsonb,
  ip_hash text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs (created_at desc);
create index if not exists admin_audit_logs_actor_idx
  on public.admin_audit_logs (admin_user_id, created_at desc);
create index if not exists admin_audit_logs_entity_idx
  on public.admin_audit_logs (entity_type, entity_id, created_at desc);

create or replace function public.admin_analytics_summary(p_days integer default 30)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with bounds as (
  select greatest(1, least(coalesce(p_days, 30), 90))::integer as days,
         date_trunc('day', now()) as today_start
),
filtered as (
  select e.*
  from public.tool_usage_events e, bounds b
  where e.occurred_at >= b.today_start - ((b.days - 1) * interval '1 day')
),
series as (
  select generate_series(
    (select today_start - ((days - 1) * interval '1 day') from bounds),
    (select today_start from bounds),
    interval '1 day'
  ) as day
),
daily as (
  select s.day,
         count(f.id) filter (where f.event_type = 'page_view')::bigint as page_views,
         count(f.id) filter (where f.event_type in ('tool_open','external_open'))::bigint as tool_opens,
         count(distinct f.visitor_hash)::bigint as unique_visitors,
         count(f.id) filter (where f.event_type = 'tool_error')::bigint as errors
  from series s
  left join filtered f
    on f.occurred_at >= s.day and f.occurred_at < s.day + interval '1 day'
  group by s.day
  order by s.day
),
top_tools as (
  select coalesce(f.tool_id, 'unknown') as tool_id,
         coalesce(t.name, f.tool_id, 'Unknown') as name,
         count(*) filter (where f.event_type in ('tool_open','external_open'))::bigint as opens,
         count(distinct f.visitor_hash)::bigint as unique_visitors,
         count(*) filter (where f.event_type = 'tool_error')::bigint as errors
  from filtered f
  left join public.tools t on t.id = f.tool_id
  where f.event_type in ('tool_open','external_open','tool_error')
    and f.tool_id is not null
  group by coalesce(f.tool_id, 'unknown'), coalesce(t.name, f.tool_id, 'Unknown')
  order by count(*) filter (where f.event_type in ('tool_open','external_open')) desc, name asc
  limit 12
),
by_type as (
  select event_type, count(*)::bigint as total
  from filtered
  group by event_type
),
totals as (
  select
    count(*) filter (where event_type = 'page_view')::bigint as page_views,
    count(*) filter (where event_type in ('tool_open','external_open'))::bigint as tool_opens,
    count(*) filter (where event_type = 'tool_error')::bigint as errors,
    count(distinct visitor_hash)::bigint as unique_visitors,
    count(*) filter (
      where occurred_at >= (select today_start from bounds)
        and event_type in ('tool_open','external_open')
    )::bigint as tool_opens_today
  from filtered
)
select jsonb_build_object(
  'days', (select days from bounds),
  'generatedAt', now(),
  'totals', jsonb_build_object(
    'pageViews', coalesce((select page_views from totals), 0),
    'toolOpens', coalesce((select tool_opens from totals), 0),
    'toolOpensToday', coalesce((select tool_opens_today from totals), 0),
    'uniqueVisitors', coalesce((select unique_visitors from totals), 0),
    'errors', coalesce((select errors from totals), 0)
  ),
  'daily', coalesce((
    select jsonb_agg(jsonb_build_object(
      'date', to_char(day, 'YYYY-MM-DD'),
      'pageViews', page_views,
      'toolOpens', tool_opens,
      'uniqueVisitors', unique_visitors,
      'errors', errors
    ) order by day)
    from daily
  ), '[]'::jsonb),
  'topTools', coalesce((
    select jsonb_agg(jsonb_build_object(
      'toolId', tool_id,
      'name', name,
      'opens', opens,
      'uniqueVisitors', unique_visitors,
      'errors', errors
    ) order by opens desc, name asc)
    from top_tools
  ), '[]'::jsonb),
  'eventTypes', coalesce((
    select jsonb_object_agg(event_type, total)
    from by_type
  ), '{}'::jsonb)
);
$$;

revoke all on function public.admin_analytics_summary(integer) from public, anon, authenticated;
grant execute on function public.admin_analytics_summary(integer) to service_role;

grant usage on schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select, insert, update, delete on table public.feedback to service_role;
grant select, insert, update, delete on table public.tool_usage_events to service_role;
grant select, insert, update, delete on table public.admin_audit_logs to service_role;
grant select on table public.tools to service_role;

notify pgrst, 'reload schema';
