-- Nexora v6.0 — Runtime JavaScript test, screenshot, dan visual validation
-- Jalankan setelah migration 004_analytics_feedback_audit.sql. Aman dijalankan ulang.

create table if not exists public.visual_baselines (
  id uuid primary key default gen_random_uuid(),
  route text not null,
  viewport text not null check (viewport in ('mobile', 'tablet', 'desktop')),
  width integer not null check (width between 240 and 2560),
  height integer not null check (height between 320 and 2000),
  fingerprint text not null,
  screenshot_hash text not null,
  threshold_percent numeric(5,2) not null default 8 check (threshold_percent between 0.5 and 40),
  thumbnail_data_url text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (route, viewport)
);

alter table public.visual_baselines enable row level security;

drop trigger if exists visual_baselines_set_updated_at on public.visual_baselines;
create trigger visual_baselines_set_updated_at
before update on public.visual_baselines
for each row execute function public.set_updated_at();

create table if not exists public.visual_test_runs (
  id bigint generated by default as identity primary key,
  route text not null,
  viewport text not null check (viewport in ('mobile', 'tablet', 'desktop')),
  status text not null check (status in ('pass', 'warning', 'fail', 'error')),
  runtime_errors integer not null default 0 check (runtime_errors >= 0),
  resource_errors integer not null default 0 check (resource_errors >= 0),
  console_errors integer not null default 0 check (console_errors >= 0),
  warnings integer not null default 0 check (warnings >= 0),
  difference_percent numeric(6,2),
  screenshot_hash text,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  report jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.visual_test_runs enable row level security;

create index if not exists visual_baselines_target_idx
  on public.visual_baselines (route, viewport);
create index if not exists visual_test_runs_target_time_idx
  on public.visual_test_runs (route, viewport, created_at desc);
create index if not exists visual_test_runs_status_time_idx
  on public.visual_test_runs (status, created_at desc);

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.visual_baselines to service_role;
grant select, insert, update, delete on table public.visual_test_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
